### ISSUE TITLE
30Mb upoad limit on local version

### ISSUE THREAD

**Issue by sdewell** [yan-cri/DEAPP-shiny#2]
Hello,

The 30Mb limit on upload is still present in the local version. Any advice to change this would be appreciated as it's the reason I installed locally. Thank you!

**Comment by sdewell** [comment]
Edited the server.R and reloaded ... seems to work. might be worth mentioning. Thanks!

**Comment by yan-cri** [comment]
Hi,

If you have data exceeds the limit of 30MB, after downloading the source code from GitHub to your local PC, please go to the server.R file, on line 34 and 35, you should see comments as below:
---
## Uploading file's size requirement (<30MB)
options(shiny.maxRequestSize = 30*1024^2)
---
Then simply provide a large samples size limit by changing it into
## Uploading file's size requirement (<50MB)
options(shiny.maxRequestSize = 50*1024^2)
Then this application would allow you to analyze data no larger than 50MB.
---
Please let me know if you have any difficulty to install DEApp to your local PC.

Best,
Yan

On Feb 24, 2019, at 12:50 PM, sdewell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

The 30Mb limit on upload is still present in the local version. Any advice to change this would be appreciated as it's the reason I installed locally. Thank you!

**Comment by sdewell** [comment]
Thank you - I was able to make it work.
